import '../styles.css';
import './router.css';
import { buildFullPdfReport } from './pdfReport.js';
import { getLeads, saveLead, updateLeadStatus, LEAD_STATUSES } from './leadsStore.js';
const CONFIG={productionPerKw:1650,buyRate:.64,sellRate:.48,installCostPerKw:2900,sqmPerKw:7,panelKw:.63,usableRoofFactor:.82,vatRate:.18,homeSystemLimitKw:22.5,defaultSelfUseShare:.4,electricityGrowthRate:.04,defaultPhone:'972547299727'};
const LOGO_SRC='https://static.wixstatic.com/media/e34422_f461fb2e8382455e8d0d7ba9d71eca1e~mv2.png/v1/fill/w_298,h_194,al_c,q_90,enc_avif,quality_auto/Solatrix%20Logo%20Sait%20Main.png';
const BASE_PATH='/roof-check', SITE_ROOT='/';
const routes=['','address','roof-type','roof-marking','obstacles','analysis','report','admin'];
const labels=['ראשי','כתובת וחשבון','סוג גג','סימון גג','מכשולים','ניתוח','דוח','Admin'];
const state={step:0,address:'',monthlyBill:850,roofType:'flat',leadName:'',leadPhone:'',points:[],surfaces:[],obstacles:[],leadSent:false,menuOpen:false,timer:null};
function stepFromPath(){const p=location.pathname.replace(/\/$/,'');const i=routes.findIndex(s=>s&&p.endsWith('/'+s));return i>0?i:(location.hash==='#admin'?7:0)} state.step=stepFromPath();
function path(s){return s?`${BASE_PATH}/${s}`:`${BASE_PATH}/`} function go(s){state.step=Math.max(0,Math.min(7,+s));history.pushState({step:state.step},'',path(routes[state.step]));render();if(state.step===5){clearTimeout(state.timer);state.timer=setTimeout(()=>go(6),900)}}
function fmt(v){return Math.round(+v||0).toLocaleString('he-IL')} function money(v){return '₪'+fmt(v)}
function logo(){return `<div class="logoMark"><img class="logoImage" src="${LOGO_SRC}" alt="Solatrix" /></div>`}
function header(){let m=[0,1,2,3,4,6].map(i=>`<a href="${path(routes[i])}" data-action="step:${i}" class="${state.step===i?'active':''}">${labels[i]}</a>`).join('');return `<header class="siteHeader ${state.menuOpen?'menuOpen':''}"><div class="headerInner"><a class="brand" href="/">${logo()}</a><div class="headerActions"><a class="headerCta" href="https://wa.me/${CONFIG.defaultPhone}" target="_blank">WhatsApp</a><button class="menuBtn" data-action="menu">${state.menuOpen?'×':'☰'}</button></div></div><nav class="mobileMenu">${m}</nav></header>`}
function dots(){return state.step&&state.step<7?`<div class="progressDots">${[1,2,3,4,5,6].map(i=>`<span class="${i<=state.step?'done':''}"></span>`).join('')}</div>`:''}
function decor(){return '<div class="cardDecor"><i></i><i></i><i></i></div>'} function floats(){return '<div class="floatingDecor"><span>☀️</span><span>⚡</span><span>🏠</span><span>📍</span></div>'} function actions(t){return `<div class="actions"><button class="primaryBtn" data-action="next">${t}</button>${state.step>1?'<button class="ghostBtn" data-action="prev">חזרה</button>':''}</div>`}
function pStr(p=state.points){return p.map(x=>`${x.x.toFixed(1)},${x.y.toFixed(1)}`).join(' ')}
function area(p){if(p.length<3)return 0;let s=0;for(let i=0;i<p.length;i++){let a=p[i],b=p[(i+1)%p.length];s+=a.x*b.y-b.x*a.y}return Math.max(20,Math.round(Math.abs(s/2)*.045))}
function currentSurface(){return state.points.length>=3?{points:pStr(),area:area(state.points),factor:1}:null}
function allSurfaces(){let s=[...state.surfaces];let d=currentSurface();if(d)s.push(d);return s.length?s:[{points:'17,58 77,42 86,78 24,88',area:74,factor:1}]}
function addPoint(e,node){let r=node.getBoundingClientRect();let x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;state.points.push({x:Math.max(0,Math.min(100,x)),y:Math.max(0,Math.min(100,y))});render()}
function finishSide(){let d=currentSurface();if(d){state.surfaces.push(d);state.points=[]}}
function calc(){let ss=allSurfaces(),roofArea=ss.reduce((a,s)=>a+s.area,0),usableArea=roofArea*CONFIG.usableRoofFactor,potential=usableArea/CONFIG.sqmPerKw,systemKw=state.roofType==='commercial'?potential:Math.min(potential,CONFIG.homeSystemLimitKw),annualProduction=systemKw*CONFIG.productionPerKw,annualConsumption=(+state.monthlyBill*12)/CONFIG.buyRate,selfConsumed=Math.min(annualProduction*CONFIG.defaultSelfUseShare,annualConsumption),exported=Math.max(annualProduction-selfConsumed,0),annualSavings=selfConsumed*CONFIG.buyRate+exported*CONFIG.sellRate,effectiveTariff=annualSavings/Math.max(annualProduction,1),selfUseShare=selfConsumed/Math.max(annualProduction,1)*100,exportShare=100-selfUseShare,costBeforeVat=systemKw*CONFIG.installCostPerKw,costWithVat=costBeforeVat*(1+CONFIG.vatRate),paybackBeforeVat=costBeforeVat/Math.max(annualSavings,1),paybackWithVat=costWithVat/Math.max(annualSavings,1);let gross25=0;for(let y=0;y<25;y++)gross25+=selfConsumed*CONFIG.buyRate*Math.pow(1+CONFIG.electricityGrowthRate,y)+exported*CONFIG.sellRate;return{systemKw,roofPotentialKw:potential,annualProduction,annualConsumption,selfConsumed,exported,annualSavings,effectiveTariff,selfUseShare,exportShare,cost:costBeforeVat,costBeforeVat,costWithVat,payback:paybackWithVat,paybackBeforeVat,paybackWithVat,profit25:gross25-costWithVat,profit25WithVat:gross25-costWithVat,gross25,avgTariff25:gross25/Math.max(annualProduction*25,1),panels:Math.max(Math.floor(systemKw/CONFIG.panelKw),1),roofArea,usableArea}}
function map(interactive=false){let surfs=allSurfaces().map((s,i)=>`<polygon class="surface ${i===allSurfaces().length-1?'active':''}" points="${s.points}"></polygon>`).join(''),line=state.points.length>1?`<polyline class="draftLine" points="${pStr()}"></polyline>`:'',pts=state.points.map((p,i)=>`<g class="draftPoint"><circle cx="${p.x}" cy="${p.y}" r="3"></circle><text x="${p.x}" y="${p.y-4}" text-anchor="middle">${i+1}</text></g>`).join('');return `<div class="mapPanel ${interactive?'interactiveMap':''}" ${interactive?'data-action="mapPoint"':''}><div class="mapBadge">${interactive?(state.points.length?state.points.length+' נקודות':'Tap to mark'):'Roof marked'}</div><div class="scanPulse"></div><svg class="roofCanvas" viewBox="0 0 100 100"><defs><pattern id="grid" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M 8 0 L 0 0 0 8" fill="none" /></pattern></defs><rect width="100" height="100" class="mapBase"></rect><rect width="100" height="100" fill="url(#grid)" class="mapGrid"></rect><path class="sunRay" d="M5 15 L35 42 M4 38 L34 52 M12 60 L42 62"></path><path class="building" d="M12 14 L86 9 L92 82 L18 90 Z"></path>${surfs}${line}${pts}</svg></div>`}
function hero(){return `<section class="screen heroScreen">${floats()}<div class="heroGrid"><div class="card centerCard heroCard">${decor()}<div class="eyebrow">Roof Check by Solatrix</div><h1>בדיקת גג סולארית</h1><p class="heroText">תוך דקה מקבלים הערכה ראשונית.</p><div class="featureChips"><span>☀️ חישוב מהיר</span><span>📍 לפי כתובת</span><span>📄 דוח PDF מלא</span></div><button class="primaryBtn large" data-action="next">התחילו בדיקת גג</button></div><div class="visualCard"><div class="orbit orbitOne"></div><div class="miniRoof"><div class="roofTop"></div><div class="panelRows"><span></span><span></span><span></span><span></span></div></div><div class="visualStats"><b>PDF</b><span>דוח מלא</span></div></div></div></section>`}
function address(){return `<section class="screen">${floats()}<div class="card focusCard">${decor()}${dots()}<div class="screenIcon">📍</div><h2>כתובת וחשבון חשמל</h2><div class="fieldGroup"><label>כתובת הגג</label><input value="${state.address}" data-field="address" placeholder="לדוגמה: החרמון 10, חיפה" /></div><div class="fieldGroup"><label>חשבון חשמל חודשי</label><input value="${state.monthlyBill}" data-field="monthlyBill" inputmode="numeric" /></div>${actions('מצא את הגג')}</div></section>`}
function roof(){return `<section class="screen">${floats()}<div class="card focusCard">${decor()}${dots()}<div class="screenIcon">🏠</div><h2>איזה סוג גג?</h2><div class="roofOptions"><button class="roofOption ${state.roofType==='flat'?'selected':''}" data-action="roof:flat"><span>▰</span><b>גג שטוח</b><small>עד 22.5 kW ביתי</small></button><button class="roofOption ${state.roofType==='sloped'?'selected':''}" data-action="roof:sloped"><span>◭</span><b>כמה צדדים</b><small>נסמן כל צד</small></button><button class="roofOption ${state.roofType==='commercial'?'selected':''}" data-action="roof:commercial"><span>▦</span><b>גג מסחרי</b><small>ללא מגבלת 22.5</small></button></div>${actions('המשך לסימון')}</div></section>`}
function draw(){let n=state.points.length;return `<section class="screen mapScreen"><div class="card mapCard">${decor()}${dots()}<div class="screenIcon">✏️</div><h2>סמנו את שטח הגג</h2><p class="subText">לחצו על פינות הגג לפי הסדר. כל לחיצה מוסיפה נקודה קטנה וקו כחול.</p>${map(true)}<div class="markStatus">${n?`סומנו ${n} נקודות${n>=3?' — אפשר להמשיך':''}`:'לחצו על פינות הגג כדי להתחיל סימון.'}</div><div class="drawFooter"><div class="actions compactActions"><button class="ghostBtn" data-action="undoPoint" ${!n?'disabled':''}>בטל נקודה</button><button class="ghostBtn" data-action="clearRoof">נקה סימון</button>${state.roofType==='sloped'&&n>=3?'<button class="primaryBtn" data-action="finishSide">סיים צד והוסף עוד</button>':''}</div><button class="nextTextBtn" data-action="next" ${n<3&&!state.surfaces.length?'disabled':''}>סיימתי</button></div></div></section>`}
function obstacles(){let items=[['ac','מזגן','❄️'],['boiler','דוד','💧'],['shade','צל','🌳'],['access','יציאה לגג','🚪'],['solar','קולטים קיימים','☀️']];return `<section class="screen mapScreen"><div class="card mapCard">${decor()}${dots()}<div class="screenIcon">🧩</div><h2>מה נמצא על הגג?</h2>${map()}<div class="obstacleGrid">${items.map(([k,l,i])=>`<button class="obstacle ${state.obstacles.includes(k)?'selected':''}" data-action="obstacle:${k}"><span>${i}</span>${l}</button>`).join('')}</div>${actions('המשך')}</div></section>`}
function analysis(){return `<section class="screen">${floats()}<div class="card centerCard analysisCard">${decor()}<div class="loader"></div><h2>מנתחים את הגג...</h2><p class="subText">בודקים שטח, ייצור, תעריף משולב ו-ROI.</p></div></section>`}
function report(){let r=calc();return `<section class="screen reportScreen">${floats()}<div class="card reportCard">${decor()}<div class="eyebrow">דוח סולארי ראשוני</div><h2>הגג מתאים למערכת של כ-${r.systemKw.toFixed(1)} kW</h2><div class="reportHeroGraphic"><div><strong>${money(r.annualSavings)}</strong><span>חיסכון שנתי</span></div><div><strong>${r.paybackWithVat.toFixed(1)}</strong><span>החזר כולל מע״מ</span></div></div><div class="resultsGrid"><div><span>עלות לפני מע״מ</span><b>${money(r.costBeforeVat)}</b></div><div><span>עלות כולל מע״מ</span><b>${money(r.costWithVat)}</b></div><div><span>ייצור שנתי</span><b>${fmt(r.annualProduction)} kWh</b></div><div><span>ערך קוט״ש ממוצע</span><b>₪${r.effectiveTariff.toFixed(3)}</b></div><div><span>החזר לפני מע״מ</span><b>${r.paybackBeforeVat.toFixed(1)} שנים</b></div><div><span>רווח 25 שנים</span><b>${money(r.profit25WithVat)}</b></div></div><div class="leadFields"><input placeholder="שם מלא" value="${state.leadName}" data-field="leadName" /><input placeholder="טלפון WhatsApp" value="${state.leadPhone}" data-field="leadPhone" /></div><button class="primaryBtn large" data-action="generatePdf">קבלו דוח PDF מלא</button>${state.leadSent?'<div class="successToast">הדוח נפתח והפנייה נשמרה.</div>':''}</div></section>`}
function admin(){let leads=getLeads();return `<section class="screen adminScreen"><div class="card adminCard"><h2>Solatrix CRM</h2><p>${leads.length} לידים</p></div></section>`}
function save(r){saveLead({name:state.leadName||'ללא שם',phone:state.leadPhone||'',address:state.address,monthlyBill:state.monthlyBill,roofType:state.roofType,surfaces:allSurfaces(),obstacles:state.obstacles,systemKw:r.systemKw,annualProduction:r.annualProduction,annualSavings:r.annualSavings,payback:r.paybackWithVat,profit25:r.profit25WithVat,status:'חדש'})}
function pdf(){finishSide();let r=calc();save(r);let html=buildFullPdfReport({report:r,state,config:CONFIG,logoSrc:LOGO_SRC,formatNumber:fmt,formatMoney:money});let w=open('','_blank');if(!w)return;w.document.open();w.document.write(html);w.document.close();state.leadSent=true;render()}
function screen(){return [hero,address,roof,draw,obstacles,analysis,report,admin][state.step]()} 
function act(a,n,e){if(n.disabled)return;if(a==='menu'){state.menuOpen=!state.menuOpen;render()}else if(a==='next'){if(state.step===3)finishSide();go(state.step+1)}else if(a==='prev')go(state.step-1);else if(a==='mapPoint')addPoint(e,n);else if(a==='undoPoint'){state.points.pop();render()}else if(a==='clearRoof'){state.points=[];state.surfaces=[];render()}else if(a==='finishSide'){finishSide();render()}else if(a==='generatePdf')pdf();else if(a.startsWith('step:'))go(a.split(':')[1]);else if(a.startsWith('roof:')){state.roofType=a.split(':')[1];state.points=[];state.surfaces=[];render()}else if(a.startsWith('obstacle:')){let v=a.split(':')[1];state.obstacles=state.obstacles.includes(v)?state.obstacles.filter(x=>x!==v):[...state.obstacles,v];render()}}
function render(){let root=document.getElementById('root');root.innerHTML=`${header()}<main class="appShell">${screen()}</main>`;root.querySelectorAll('[data-action]').forEach(n=>n.addEventListener('click',e=>{e.preventDefault();act(n.dataset.action,n,e)}));root.querySelectorAll('[data-field]').forEach(n=>n.addEventListener('input',()=>state[n.dataset.field]=n.value))}
addEventListener('popstate',()=>{state.step=stepFromPath();render()});render();